ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    GPU_GPU: False
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_SENSOR', 'GPS_SENSOR', 'COMPASS_SENSOR', 'STOP_ORACLE', 'POINTGOAL_WITH_GPS_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'NOISY_POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_SENSOR:
    GOAL_FORMAT: CARTESIAN
    DIMENSIONALITY: 2
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: CARTESIAN
    DIMENSIONALITY: 2
  POINTGOAL_SENSOR:
    GOAL_FORMAT: CARTESIAN
    DIMENSIONALITY: 2
  NOISY_POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: CARTESIAN
    DIMENSIONALITY: 2
    TYPE: NoisyPointGoalWithGPSCompassSensor
  GOAL_SENSOR_UUID: pointgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz